-- PostgreSQL baseline for a new, empty database.
-- Additive only: no DROP, TRUNCATE, or data replacement.

CREATE TABLE IF NOT EXISTS don_vi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_don_vi VARCHAR(20) UNIQUE NOT NULL,
    ten_don_vi VARCHAR(255) NOT NULL,
    loai_don_vi VARCHAR(50),
    don_vi_cha_id INTEGER REFERENCES don_vi(id),
    dia_chi VARCHAR(255),
    ghi_chu TEXT
);

CREATE TABLE IF NOT EXISTS chuc_vu (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_chuc_vu VARCHAR(150) NOT NULL,
    cap_bac INTEGER NOT NULL,
    mo_ta VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS can_bo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    so_hieu_can_bo VARCHAR(30) UNIQUE,
    don_vi_id INTEGER REFERENCES don_vi(id),
    chuc_vu_id INTEGER REFERENCES chuc_vu(id),
    don_vi_co_so VARCHAR(255),
    ho_ten_khai_sinh VARCHAR(150) NOT NULL,
    ten_goi_khac VARCHAR(150),
    gioi_tinh VARCHAR(5),
    anh_chan_dung VARCHAR(255),
    ngay_sinh DATE,
    noi_sinh VARCHAR(255),
    que_quan_xa VARCHAR(100),
    que_quan_huyen VARCHAR(100),
    que_quan_tinh VARCHAR(100),
    noi_o_hien_nay VARCHAR(255),
    dien_thoai VARCHAR(20),
    email VARCHAR(120),
    dan_toc VARCHAR(50),
    ton_giao VARCHAR(50),
    thanh_phan_gia_dinh VARCHAR(255),
    nghe_nghiep_truoc_tuyen_dung VARCHAR(255),
    ngay_tuyen_dung DATE,
    noi_tuyen_dung VARCHAR(255),
    ngay_vao_co_quan_hien_tai DATE,
    ngay_tham_gia_cach_mang DATE,
    ngay_vao_dang DATE,
    ngay_chinh_thuc_dang DATE,
    ngay_tham_gia_to_chuc_ct_xh VARCHAR(255),
    ngay_nhap_ngu DATE,
    ngay_xuat_ngu DATE,
    quan_ham_chuc_vu_cao_nhat VARCHAR(150),
    trinh_do_giao_duc_pho_thong VARCHAR(50),
    hoc_ham_hoc_vi_cao_nhat VARCHAR(150),
    ly_luan_chinh_tri VARCHAR(50),
    ngoai_ngu VARCHAR(150),
    cap_uy_hien_tai VARCHAR(150),
    cap_uy_kiem VARCHAR(150),
    chuc_vu VARCHAR(255),
    phu_cap_chuc_vu VARCHAR(50),
    cong_tac_chinh_dang_lam VARCHAR(255),
    ngach_cong_chuc VARCHAR(150),
    ma_so_ngach VARCHAR(30),
    bac_luong VARCHAR(20),
    he_so_luong NUMERIC(4,2),
    luong_tu_thang_nam VARCHAR(20),
    danh_hieu_duoc_phong VARCHAR(255),
    so_truong_cong_tac VARCHAR(255),
    cong_viec_lam_lau_nhat VARCHAR(255),
    tinh_trang_suc_khoe VARCHAR(100),
    chieu_cao_cm NUMERIC(5,1),
    can_nang_kg NUMERIC(5,1),
    nhom_mau VARCHAR(5),
    so_cmnd_cccd VARCHAR(20),
    thuong_binh_loai VARCHAR(50),
    gia_dinh_liet_si BOOLEAN DEFAULT FALSE,
    trang_thai VARCHAR(30) DEFAULT 'Đang công tác',
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dao_tao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_bo_id INTEGER NOT NULL REFERENCES can_bo(id) ON DELETE CASCADE,
    ten_truong VARCHAR(255), nganh_hoc VARCHAR(255), tu_nam INTEGER, den_nam INTEGER,
    hinh_thuc_hoc VARCHAR(50), van_bang_chung_chi VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS qua_trinh_cong_tac (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_bo_id INTEGER NOT NULL REFERENCES can_bo(id) ON DELETE CASCADE,
    tu_thang_nam VARCHAR(20), den_thang_nam VARCHAR(20), chuc_danh_don_vi VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS qua_trinh_luong (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_bo_id INTEGER NOT NULL REFERENCES can_bo(id) ON DELETE CASCADE,
    thang_nam VARCHAR(20), ngach_bac VARCHAR(100), he_so_luong NUMERIC(4,2)
);

CREATE TABLE IF NOT EXISTS khen_thuong (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_bo_id INTEGER NOT NULL REFERENCES can_bo(id) ON DELETE CASCADE,
    noi_dung VARCHAR(255), nam INTEGER
);

CREATE TABLE IF NOT EXISTS ky_luat (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_bo_id INTEGER NOT NULL REFERENCES can_bo(id) ON DELETE CASCADE,
    hinh_thuc VARCHAR(150), cap_quyet_dinh VARCHAR(150), ly_do VARCHAR(255), nam INTEGER
);

CREATE TABLE IF NOT EXISTS lich_su_ban_than (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_bo_id INTEGER NOT NULL REFERENCES can_bo(id) ON DELETE CASCADE,
    loai VARCHAR(50), noi_dung TEXT
);

CREATE TABLE IF NOT EXISTS quan_he_nuoc_ngoai (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_bo_id INTEGER NOT NULL REFERENCES can_bo(id) ON DELETE CASCADE,
    loai VARCHAR(50), noi_dung TEXT
);

CREATE TABLE IF NOT EXISTS quan_he_gia_dinh (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_bo_id INTEGER NOT NULL REFERENCES can_bo(id) ON DELETE CASCADE,
    nhom VARCHAR(20), quan_he VARCHAR(30), ho_ten VARCHAR(150), nam_sinh INTEGER, thong_tin TEXT
);

CREATE TABLE IF NOT EXISTS hoan_canh_kinh_te (
    can_bo_id INTEGER PRIMARY KEY REFERENCES can_bo(id) ON DELETE CASCADE,
    nguon_thu_nhap_luong VARCHAR(255), nguon_thu_nhap_khac VARCHAR(255), nha_o_loai VARCHAR(100),
    nha_o_dien_tich_m2 NUMERIC(8,2), dat_o_duoc_cap_m2 NUMERIC(8,2), dat_o_tu_mua_m2 NUMERIC(8,2),
    dat_san_xuat_kinh_doanh TEXT
);

CREATE TABLE IF NOT EXISTS tai_khoan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_dang_nhap VARCHAR(50) UNIQUE NOT NULL,
    mat_khau_hash VARCHAR(255) NOT NULL,
    ho_ten VARCHAR(150), vai_tro VARCHAR(20) DEFAULT 'viewer',
    can_bo_id INTEGER REFERENCES can_bo(id)
);

CREATE INDEX IF NOT EXISTS idx_canbo_hoten ON can_bo(ho_ten_khai_sinh);
CREATE INDEX IF NOT EXISTS idx_canbo_donvi ON can_bo(don_vi_id);
CREATE INDEX IF NOT EXISTS idx_canbo_chucvu ON can_bo(chuc_vu_id);
CREATE INDEX IF NOT EXISTS idx_canbo_sohieu ON can_bo(so_hieu_can_bo);
CREATE INDEX IF NOT EXISTS idx_canbo_cccd ON can_bo(so_cmnd_cccd);
