-- PostgreSQL migration: run once against the configured database.
-- This migration only adds the requested column, table, constraints and indexes.

ALTER TABLE chuc_vu ADD COLUMN IF NOT EXISTS ma_chuc_vu VARCHAR(30);

CREATE UNIQUE INDEX IF NOT EXISTS uq_chuc_vu_ma_chuc_vu
    ON chuc_vu (ma_chuc_vu)
    WHERE ma_chuc_vu IS NOT NULL;

CREATE TABLE IF NOT EXISTS gioi_han_chuc_vu_don_vi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_vi_id INTEGER NOT NULL REFERENCES don_vi(id),
    chuc_vu_id INTEGER NOT NULL REFERENCES chuc_vu(id),
    so_luong_toi_da INTEGER NOT NULL DEFAULT 1,
    ghi_chu VARCHAR(255),
    CONSTRAINT uq_gioi_han_chuc_vu_don_vi UNIQUE (don_vi_id, chuc_vu_id),
    CONSTRAINT ck_gioi_han_so_luong_duong CHECK (so_luong_toi_da >= 1)
);

CREATE INDEX IF NOT EXISTS ix_gioi_han_don_vi_id
    ON gioi_han_chuc_vu_don_vi (don_vi_id);
CREATE INDEX IF NOT EXISTS ix_gioi_han_chuc_vu_id
    ON gioi_han_chuc_vu_don_vi (chuc_vu_id);
CREATE INDEX IF NOT EXISTS ix_don_vi_ma_don_vi
    ON don_vi (ma_don_vi);
CREATE INDEX IF NOT EXISTS ix_chuc_vu_ma_chuc_vu
    ON chuc_vu (ma_chuc_vu);